utilities_configuration:
    resource: "@UtilitiesConfigurationBundle/Resources/config/routing.yml"
    prefix:   /

users_users:
    resource: "@UsersUsersBundle/Resources/config/routing.yml"
    prefix:   /

users_security:
    resource: "@UsersSecurityBundle/Resources/config/routing.yml"
    prefix:   /

products_product:
    resource: "@ProductsProductBundle/Resources/config/routing.yml"
    prefix:   /
    
    
    
    Hola

