# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    user_profile_provider.class: Users\UserBundle\Entity\UserProvider
    system_configuration.class: Utilities\ConfigurationBundle\Controller\ConfigurationController

services:
    user_profile_provider:
        class: %user_profile_provider.class%
        arguments: [@doctrine, @service_container]
    system_configuration:
        class: %system_configuration.class%