<?php

namespace Products\ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderByName($year){
        return $this->getEntityManager()->createQuery(
            'SELECT p
            FROM ProductsProductBundle:Product p
            WHERE p.productionYear > :year
            ORDER BY p.title ASC'       
        )->setParameter("year", $year)->getResult(); //setParametar garantiza que no tengamos inyección de código
    }
}
