homepage:
    path: /{_locate}
    defaults: { _controller: ProductsProductBundle:Products:index, _locate: en }
    requirements:
        _locate: en|fr
    
products_product_homepage:
    path: /products
    defaults: { _controller: ProductsProductBundle:Products:index }


product_view:
    path: /product/{id_product}
    defaults: { _controller: ProductsProductBundle:Products:getProduct, id_product: 1 }
    requirements:
        id_product: \d+


product_edit:
    path: /product/edit/{id_product}
    defaults: { _controller: ProductsProductBundle:Products:editProduct}
    
    
product_delete:
    path: /product/delete/{id_product}
    defaults: { _controller: ProductsProductBundle:Products:deleteProduct}

product_new:
    path: /product/new
    defaults: { _controller: ProductsProductBundle:Products:newProduct}
